### ISSUE TITLE
how to Create trigger.

### ISSUE THREAD

**Issue by 23bca263** [vtcbca/internal-exam-23bca263#2]
how to Create trigger to check product rate and qty is not 0. Write product table data into csv file using writer object .i  could not understand this please give me answer

**Comment by amitvtcbb** [comment]
please check ppt to create trigger. you have to create trigger for data validation means "before insert" trigger. in which you have to check qty and rate >0. Please download and read ppt of unit 1. where i explain one before insert trigger and explain how to verify email address.
